//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCWindowsInformation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCWindowsInformation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_1394Controller
        ///Win32_1394ControllerDevice
        ///Win32_Account
        ///Win32_AccountSID
        ///Win32_ACE
        ///Win32_ActionCheck
        ///Win32_AllocatedResource
        ///Win32_ApplicationCommandLine
        ///Win32_ApplicationService
        ///Win32_AssociatedBattery
        ///Win32_AssociatedProcessorMemory
        ///Win32_BaseBoard
        ///Win32_BaseService
        ///Win32_Battery
        ///Win32_Binary
        ///Win32_BindImageAction
        ///Win32_BIOS
        ///Win32_BootConfiguration
        ///Win32_Bus
        ///Win32_CacheMemory
        ///Win32_CDROMDrive
        ///Win32_CheckCheck
        ///Win32_CIMLogicalDeviceCIMDataFile
        ///Win32_ClassicCOMApplicationClasses [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WMIClassesFile {
            get {
                return ResourceManager.GetString("WMIClassesFile", resourceCulture);
            }
        }
    }
}
